"""
verdict.py — the re-execution VERDICT GATE. The trust core of the pipeline.

A campaign break is only a *candidate*. It becomes a CONFIRMED finding ONLY after its
lowered Foundry PoC:
   (1) COMPILES        (`forge build`)          — a non-renderable value fails here → SUSPECTED
   (2) RE-EXECUTES the SPECIFIC property break   — keyed on an invariant marker in the
                                                   revert reason, NOT the exit code and NOT
                                                   "any revert" (that last mistake lets an
                                                   unrelated revert masquerade as a finding)
   (3) ASSERTS HARM    (a consequence, not just "the call was possible")
Anything short of all three → SUSPECTED, with the exact failing step. Never a false CONFIRMED.

stdlib only. Uses real wall-clock-bounded subprocess (proc.run_bounded).
"""
from __future__ import annotations

import re

from proc import run_bounded
from render import render_call, asserts_harm


def invariant_marker(inv_id):
    """The hyphenated id embedded in the PoC's harm assertion revert reason. Chosen so it
    appears ONLY in the revert reason — never in a sanitized test-function name — so an
    unrelated revert in the same test cannot be mistaken for a reproduction."""
    return inv_id


def sanitize(inv_id):
    """A valid Solidity identifier fragment (underscores) for the test function name."""
    return re.sub(r"[^A-Za-z0-9]", "_", inv_id)


def forge_build(target, timeout_s=180):
    return run_bounded(["forge", "build"], timeout_s, cwd=str(target))


def forge_test(target, test_name, timeout_s=180):
    return run_bounded(["forge", "test", "--match-test", test_name, "-vv"], timeout_s, cwd=str(target))


def reproduces_specific_break(output, marker):
    """True only if a test FAILED *and* the failure carries the invariant-specific marker.

    This is the R7 fix: exit code / "some test reverted" is not enough — an unrelated
    revert (wrong string, OOG, a different require) must NOT be accepted as reproduction.
    """
    out = output or ""
    failed = ("[FAIL" in out) or re.search(r"\bFAIL(ED|ing)\b", out) is not None
    return bool(failed and marker and (marker in out))


def lower_and_verify(target, poc_source, test_name, marker, timeout_s=180):
    """Run the three-gate verdict. Returns (verdict, reason, raw_output).

    verdict ∈ {"CONFIRMED", "SUSPECTED"}.
    """
    rc, out = forge_build(target, timeout_s)
    if rc != 0:
        return "SUSPECTED", "poc did not compile", out
    rc, out = forge_test(target, test_name, timeout_s)
    if not reproduces_specific_break(out, marker):
        return "SUSPECTED", "did not reproduce the specific property break", out
    if not asserts_harm(poc_source):
        return "SUSPECTED", "no harm assertion — mechanism only", out
    return "CONFIRMED", "poc compiled, re-executed the specific break, asserted harm", out


# --------------------------------------------------------- reproducer contract assembly (Chimera path)

def render_reproducer_contract(sequences, import_line, contract_name="MedusaReproducers",
                               base="CryticToFoundry"):
    """Assemble a Foundry reproducer .t.sol that replays each normalized failing sequence
    against the Chimera harness, using TYPE-AWARE rendering (render_call). Never raises on a
    bool/array/tuple arg — that was the v0.2 crash; here such a value renders, and if a value
    is truly unrenderable the file simply fails `forge build` and the CE stays SUSPECTED."""
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.20;",
        "",
        "// AUTO-GENERATED by `fuzzpipe triage` from failing fuzzer sequences.",
        "// Replays each broken-invariant call sequence against the Chimera harness.",
        import_line,
        "",
        "contract %s is %s {" % (contract_name, base),
    ]
    for i, (fname, seq) in enumerate(sequences, 1):
        lines.append("    // from %s" % fname)
        lines.append("    function test_repro_%d() public {" % i)
        for step in seq:
            if step.get("time_delay"):
                lines.append("        vm.warp(block.timestamp + %d);" % step["time_delay"])
            if step.get("block_delay"):
                lines.append("        vm.roll(block.number + %d);" % step["block_delay"])
            for src in render_call(i, step["method"], step.get("values", []), step.get("types", [])):
                lines.append("        " + src)
        lines.append("        // TODO(skill): add the HARM assertion for the broken invariant here")
        lines.append("        // (assert the consequence — who loses what — not just that the call ran).")
        lines.append("    }")
        lines.append("")
    lines.append("}")
    return "\n".join(lines)
