from __future__ import annotations
import json
import re
from typing import Any

# --- type-aware rendering (copied from cli/render.py) ---

def parse_types(signature: str) -> list[str]:
    """Extract the ABI arg types from a canonical signature."""
    if not signature or "(" not in signature:
        return []
    inner = signature[signature.index("(") + 1: signature.rindex(")")]
    if not inner.strip():
        return []
    types, depth, cur = [], 0, []
    for ch in inner:
        if ch in "([":
            depth += 1
            cur.append(ch)
        elif ch in ")]":
            depth -= 1
            cur.append(ch)
        elif ch == "," and depth == 0:
            types.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur:
        types.append("".join(cur).strip())
    return types


def sol_scalar(value: Any, t: str) -> str:
    """Render one scalar value as a Solidity literal of ABI type `t`."""
    t = (t or "").strip()
    if t == "bool":
        return "true" if (value is True or str(value).lower() == "true") else "false"
    if t.startswith(("uint", "int")):
        return str(int(value))                                   # decimal literal
    if t == "address":
        s = str(value)
        return "address(%s)" % (s if s.startswith("0x") else hex(int(value)))
    if t.startswith("bytes") and t != "bytes":                  # fixed bytesN
        s = str(value)
        return "%s(%s)" % (t, s if s.startswith("0x") else "0x" + s)
    if t == "bytes":                                            # dynamic bytes
        s = str(value)
        return 'hex"%s"' % (s[2:] if s.startswith("0x") else s)
    if t == "string":
        return json.dumps(str(value))                           # quoted + escaped
    # unknown/fallback: keep hex verbatim, else a quoted string (compile-check backstops)
    s = str(value)
    return s if s.startswith("0x") else json.dumps(s)


def _tuple_parts(v: Any) -> list[Any]:
    if isinstance(v, dict):
        return list(v.values())
    if isinstance(v, (list, tuple)):
        return list(v)
    return [v]


def render_call(idx: int, method: str, values: list[Any], types: list[str]) -> list[str]:
    """Statement lines for one replayed call. Scalars render inline; dynamic arrays and tuples
    get a valid memory prelude so the emitted Solidity actually compiles. Returns a list of
    source lines ending in the call. `types` is threaded in from `parse_types(signature)`."""
    values = list(values or [])
    types = list(types or [])
    if len(types) < len(values):                    # tolerate schema drift / missing types
        types = types + [""] * (len(values) - len(types))

    prelude, args = [], []
    for j, (v, t) in enumerate(zip(values, types)):
        t = (t or "").strip()
        if t.endswith("[]"):                        # dynamic array -> memory prelude
            base, var = t[:-2], "_a%s_%s" % (idx, j)
            elems = v if isinstance(v, (list, tuple)) else [v]
            prelude.append("%s[] memory %s = new %s[](%d);" % (base, var, base, len(elems)))
            prelude += ["%s[%d] = %s;" % (var, k, sol_scalar(el, base)) for k, el in enumerate(elems)]
            args.append(var)
        elif t.startswith(("(", "tuple")):          # tuple/struct -> inline tuple literal
            parts = _tuple_parts(v)
            rendered = [sol_scalar(p, "uint256") if isinstance(p, int) and not isinstance(p, bool)
                        else json.dumps(str(p)) for p in parts]
            args.append("(" + ", ".join(rendered) + ")")
        else:
            args.append(sol_scalar(v, t))
    return prelude + ["this.%s(%s);" % (method, ", ".join(args))]


# --- reproducer contract assembly ---

def render_reproducer_contract(
    sequences: list[tuple[str, list[dict]]],
    import_line: str,
    contract_name: str = "MedusaReproducers",
    base: str = "CryticToFoundry",
) -> str:
    """Assemble a Foundry reproducer .t.sol that replays each normalized failing sequence
    against the Chimera harness, using TYPE-AWARE rendering (render_call). Never raises on a
    bool/array/tuple arg — that was the v0.2 crash; here such a value renders, and if a value
    is truly unrenderable the file simply fails `forge build` and the CE stays SUSPECTED."""
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.20;",
        "",
        "// AUTO-GENERATED by `fuzzpipe triage` from failing fuzzer sequences.",
        "// Replays each broken-invariant call sequence against the Chimera harness.",
        import_line,
        "",
        "contract %s is %s {" % (contract_name, base),
    ]
    for i, (fname, seq) in enumerate(sequences, 1):
        lines.append("    // from %s" % fname)
        lines.append("    function test_repro_%d() public {" % i)
        for step in seq:
            if step.get("time_delay"):
                lines.append("        vm.warp(block.timestamp + %d);" % step["time_delay"])
            if step.get("block_delay"):
                lines.append("        vm.roll(block.number + %d);" % step["block_delay"])
            for src in render_call(i, step["method"], step.get("values", []), step.get("types", [])):
                lines.append("        " + src)
        lines.append("        // TODO(skill): add the HARM assertion for the broken invariant here")
        lines.append("        // (assert the consequence — who loses what — not just that the call ran).")
        lines.append("    }")
        lines.append("")
    lines.append("}")
    return "\n".join(lines)